services:
  - type: web
    name: muc-off-sharepoint-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: TENANT_ID
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: SITE_ID
        sync: false
      - key: DRIVE_ID
        sync: false
